# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages
#       Kalderimis & Nagy, Windows is Available (Early Release), Oct 10 2018, https://blog.travis-ci.com/2018-10-11-windows-early-release
#       Miniconda (Python 3) 4.5.11, Chocolatey Gallery, https://chocolatey.org/packages/miniconda3
#       The Windows Build Environment, https://docs.travis-ci.com/user/reference/windows/
#       Build times out because no output was received, https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

os :
- linux
- osx
- windows

language : bash

env:
  - TOXENV=3.6
  - TOXENV=3.7
  - TOXENV=nightly

matrix:
  allow_failures:
    - os : windows
      language : bash
      env: TOXENV=3.6
    - os : windows
      language : bash
      env: TOXENV=3.7
    - os : windows
      language : bash
      env: TOXENV=nightly
  fast_finish: true

before_install:
  # Obtain miniconda installer
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi

install:
  # Install miniconda
  # https://docs.travis-ci.com/user/reference/windows/#support
  # https://chocolatey.org/packages/miniconda3/4.5.11
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda:$HOME/miniconda/bin:$PATH";
      hash -r;
    elif  [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install miniconda3 --params="'/AddToPath:1'";
      export PATH="/c/tools/miniconda3/scripts:/c/tools/miniconda3/:$PATH";
    fi
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Conda setup options
  # To help debugging
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  # Useful for debugging any issues with conda
  - conda info -a
  # Apply python module recipies
  - if [[ "$TOXENV" == "3.6" ]]; then
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.3.6.yml;
    elif [[ "$TOXENV" == "3.7" ]]; then
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.3.7.yml;
    else
      conda env create -n test-environment python=$TOXENV -f ./tests/environment.nightly.yml;
    fi
  - source activate test-environment
  - conda list

script: cd tests && travis_wait py.test -s
notifications:
    email:
        - kangwon.lee.edu@gmail.com
