# ref : Francesco Mosconi, Travis + Anaconda + Jupyter, https://github.com/ghego/travis_anaconda_jupyter
#       Anaconda Inc., Using conda with Travis CI, Conda documentation, https://conda.io/docs/user-guide/tasks/use-conda-with-travis-ci.html
#       CodeChat, .travis.yml - Travis CI configuration, https://pythonhosted.org/CodeChat/.travis.yml.html
#       Travis CI, Python example (unsupported languages), https://docs.travis-ci.com/user/multi-os/#python-example-unsupported-languages
#       Kalderimis & Nagy, Windows is Available (Early Release), Oct 10 2018, https://blog.travis-ci.com/2018-10-11-windows-early-release
#       Miniconda (Python 3) 4.5.11, Chocolatey Gallery, https://chocolatey.org/packages/miniconda3
#       The Windows Build Environment, https://docs.travis-ci.com/user/reference/windows/
#       Build times out because no output was received, https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
#       QCGrids : a numerical integration library for quantum chemistry, https://github.com/theochem/qcgrids/
#       Caching Dependencies and Directories, https://docs.travis-ci.com/user/caching/
#       Caching is now enabled in Windows with rewritten caching utility, https://changelog.travis-ci.com/caching-is-now-enabled-in-windows-with-rewritten-caching-utility-76161
#       To which folder does Chocolatey download the packages before installing them?, https://stackoverflow.com/questions/38421395/to-which-folder-does-chocolatey-download-the-packages-before-installing-them


language : shell

env:
  - CONDA_PYTHON=3.7
  - CONDA_PYTHON=3.7.1
  - CONDA_PYTHON=3.7.3
  - CONDA_PYTHON=nightly

os :
  - linux
  - osx
  - windows

matrix:
  exclude:
    - os: linux
      env: CONDA_PYTHON=3.7
    - os: windows
      env: CONDA_PYTHON=3.7
    - os: linux
      env: CONDA_PYTHON=3.7.3
    - os: osx
      env: CONDA_PYTHON=nightly
    - os: windows
      env: CONDA_PYTHON=nightly

before_cache:
  - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history $HOME/miniconda/envs/test-environment/conda-meta/history $HOME/miniconda/lib/python3.6/__pycache__ $HOME/miniconda/lib/python3.7/__pycache__;
  - touch $HOME/miniconda/conda-meta/history;
  - set -x

cache :
  directories:
    - $HOME/download
    - $HOME/miniconda

before_install:
  - . tests/before_install_nix_win_cache.sh

install:
  # Install miniconda
  - . tests/install_nix_win_cache.sh

script: cd tests && travis_wait py.test -n auto

