name: Check links in ipynb

on: 
  push:

jobs:
  badges:
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install pytest requests jupyter

    - name: check links
      id: links
      run: python -m pytest -k 'links' ./tests
