name: Add Colab Badges

on: 
  push:

jobs:
  badges:
    name: Add Google Colab Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 20
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s
