name: CI

on: 
  schedule:
    - cron: '45 01 30 * *'
  push:
  fork:

jobs:
  test_ipynb:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: ["2021.11"]
      fail-fast: false
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: cache test-environment
      uses: actions/cache@v3
      with:
        path: $CONDA/envs/test-environment
        key: ${{ runner.os }}-${{ matrix.anaconda }}

    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh

    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh

  test_ipynb_nightly:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: [nightly]
      fail-fast: false
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh

    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
