name: CI

on: [push]

jobs:
  build:
    name: FirstAttempt
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: before install (linux)
      env:
        WORKFLOWS_OS: linux
        HOME: $RUNNER_WORKSPACE
        CONDA_PYTHON: 3.7.3
      run: |
        echo "env ========================================"
        env
        echo "miniconda paths ============================"
        export MINICONDA_PATH=$CONDA
        export MINICONDA_SUB_PATH=$MINICONDA_PATH/bin
        echo "miniconda lib paths ========================"
        export MINICONDA_LIB_BIN_PATH=$MINICONDA_PATH/Library/bin
        echo "exporting a new path ======================="
        export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$MINICONDA_LIB_BIN_PATH:$PATH"
        echo "checking python ============================"
        python --version
        echo "init conda ================================="
        $MINICONDA_PATH/etc/profile.d/conda.sh
        echo "hash -r ===================================="
        hash -r
        echo "print time ================================="
        echo The time was ${{ steps.outputs.time }}
