name: CI

on: 
  schedule:
    - cron: '45 01 30 * *'
  push:
  fork:

jobs:
  test_ipynb:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: ["2021.11"]
      fail-fast: false
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: build environment
      run: |
        $CONDA/bin/conda config --set always_yes yes --set changeps1 no;
        $CONDA/bin/conda update --quiet conda;
        $CONDA/bin/conda info -a
        $CONDA/bin/conda env create --name test-environment --file ./tests/environment.${{ matrix.anaconda }}.yml

    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: |
        source $CONDA/bin/conda activate test-environment
        $CONDA/bin/conda list
        which python
        python -m pytest --numprocesses=auto -k 'not (links or update_nmisp_py)' tests/

  test_ipynb_nightly:
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: [nightly]
      fail-fast: false
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3

    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh

    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh
