name: CI

on: 
  schedule:
    - cron: '45 01 30 * *'
  push:
  fork:

jobs:
  badges:
    name: Add Google Colab Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install bs4 jupyter lxml

    - name: Add/Update badges
      id: badges
      run: python ./utils/add_colab_main_buttons.py

    - name: Commit & push
      id: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message : Add Github badges or remove ipynb `id`s

  test_ipynb:
    needs: badges
    name: ${{ matrix.anaconda }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        anaconda: [2021.04, nightly]
      fail-fast: false
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v1
    - name: build environment
      env:
        CONDA_PYTHON: ${{ matrix.anaconda }}
      run: bash ./.github/workflows/build_env.sh
    - name: pytest
      env:
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: bash ./.github/workflows/run_test.sh

  test_links:
    needs: badges
    name: Check links in ipynb
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: setup environment
      id: setup
      run: python -m pip install pytest requests jupyter

    - name: check links
      id: links
      run: python -m pytest -k 'links or update_nmisp_py' ./tests

  update_nmisp_py:
    needs: [test_ipynb, test_links]
    name: Update nmisp_py
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - name: checkout
      id: checkout
      uses: actions/checkout@v3

    - name: run nmisp_py updater
      id: updater
      env:
        LOGIN_INFO: ${{ secrets.LOGIN_INFO }}
      run: python ./utils/update_nmisp_py.py
