name: CI

on: [push]

jobs:
  build:
    name: FirstAttempt
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: before install (linux)
      env:
        WORKFLOWS_OS: linux
        HOME: ./
      run: |
        echo "pwd ========================================"
        pwd
        echo "env ========================================"
        env
        echo "miniconda paths ============================"
        export MINICONDA_PATH=$HOME/miniconda
        export MINICONDA_SUB_PATH=$MINICONDA_PATH/bin
        echo "miniconda lib paths ========================"
        export MINICONDA_LIB_BIN_PATH=$MINICONDA_PATH/Library/bin
        echo "download miniconda ========================="
        mkdir -p $HOME/download
        echo "downloading miniconda.sh for linux ========="
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        echo "installing miniconda lib paths ============="
        bash $HOME/download/miniconda.sh -b -u -p $MINICONDA_PATH
        echo "exporting a new path ======================="
        export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$MINICONDA_LIB_BIN_PATH:$PATH"
        echo "checking python ============================"
        python --version
        echo "print time ================================="
        echo The time was ${{ steps.outputs.time }}
