name: CI

on: [push]

jobs:
  build:
    name: FirstAttempt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
        include:
          - os: ubuntu-18.04
            shell: bash
            bashrc: .bashrc
          - os: windows-2016
            shell: powershell
            bashrc: .bash_profile
    
    steps:
    - uses: actions/checkout@v1
    - name: test_ipynb
      env:
        WORKFLOWS_OS: ${{ matrix.os }}
        HOME: ..
        SHELL: ${{ matrix.shell }}
        BASHRC: ${{ matrix.bashrc }}
        CONDA_PYTHON: 3.7.3
        TEST_IPYNB_IGNORE_FOLDER: tutorial
      run: . ./.github/workflows/create_env_and_test.sh
